Repository deco-cx/deco, pull requests merged in 2023-05, with the labels that each got.

#222 Auto generated releases
  CHANGELOG.md
  deno.lock
  scripts/changelog.ts
  scripts/release.ts
  utils/update.ts
Labels: enhancement

#224 fix: normalized loader signature
  blocks/propsLoader.ts
  blocks/section.ts
  deno.lock
  engine/core/utils.ts
  mod.ts
  schemas.gen.json
  types.ts
Labels: enhancement, breaking-change

#221 Allow throwing exceptions to return responses
  blocks/route.ts
  blocks/workflow.ts
  deno.lock
  deps.ts
  engine/errors.ts
  handlers/fresh.ts
  mod.ts
Labels: enhancement

#231 fix: Add RequestIdleCallback polyfill
  components/LiveControls.tsx
  components/LivePolyfills.tsx
  deno.lock
  pages/LivePage.tsx
  routes/live/previews/[...block].tsx
Labels: bug

#226 feat: Inline Editor handle outside block and slot sections
  components/LivePageEditor.tsx
  engine/core/resolver.ts
  pages/LivePage.tsx
  sections/PageInclude.tsx
  sections/UseSlot.tsx
Labels: enhancement

#234 fix: page.id
  blocks/section.ts
  blocks/utils.ts
  engine/block.ts
  handlers/devPage.ts
  pages/LivePage.tsx
  routes/live/invoke/index.ts
  routes/live/previews/[...block].tsx
  scripts/upgrade.ts
  utils/object.ts
Labels: bug

#237 Allow configuring catchall handler by just setting a handler
  engine/configstore/pages.ts
  routes/[...catchall].tsx
  schemas.gen.json
Labels: enhancement

#233 chore: Pass renderSection via context
  engine/block.ts
  pages/LivePage.tsx
  sections/PageInclude.tsx
  sections/UseSlot.tsx
Labels: enhancement

#238 Priorize JSDoc title over prop name.
  deno.lock
  engine/schema/schemeable.test.ts
  engine/schema/schemeable.test.types.ts
  engine/schema/schemeable.ts
Labels: bug

#240 Performance improvements around `deno task start` 🏎
  deno.lock
  dev.ts
  engine/schema/reader.ts
  engine/schema/utils.ts
  live.ts
  routes/live/_meta.ts
  utils/update.ts
Labels: enhancement

#241 Reuse storage space for doc cache
  engine/schema/utils.ts
Labels: enhancement

#239 Do not transform loaders into async loaders unnecessarily
  blocks/loader.ts
  blocks/utils.ts
  deno.lock
Labels: enhancement

#242 Allow only valid cookie names on audience name
  flags/audience.ts
  handlers/proxy.ts
  schemas.gen.json
Labels: bug

#243 Allow level-3 nested properties to be resolved
  deno.lock
  engine/configstore/pages.ts
  engine/core/mod.test.ts
  engine/core/resolver.ts
  flags/audience.ts
  handlers/routesSelection.ts
Labels: enhancement

#244 Allow proxies and redirects to be created through v1 UI
  engine/configstore/constants.ts
  engine/configstore/fs.ts
  engine/configstore/pages.ts
  engine/configstore/provider.ts
Labels: enhancement

#249 Allow supabase to be configured through env var and expose release endpoint
  blocks/function.ts
  blocks/route.ts
  compatibility/v0/editorData.ts
  deno.lock
  engine/core/mod.ts
  engine/fresh/manifest.ts
  engine/fresh/manifestGen.ts
  engine/releases/constants.ts
  engine/releases/fs.ts
  engine/releases/pages.ts
  engine/releases/provider.ts
  engine/releases/release.ts
  engine/releases/supabaseProvider.ts
  handlers/routesSelection.ts
  live.gen.ts
  live.ts
  meta.json
  routes/live/invoke/index.ts
  routes/live/release.ts
  routes/live/workbench.ts
  schemas.gen.json
  supabase.ts
  types.ts
  utils/object.ts
Labels: ignore-for-release

#251 Allow users to be segmented by device
  deno.lock
  live.gen.ts
  matchers/MatchDevice.ts
  schemas.gen.json
Labels: enhancement

#255 feat: Improve section name and controls layout
  components/LivePageEditor.tsx
Labels: enhancement

#260 Fix invoke 500's responses and allow returning a bad request error
  blocks/route.ts
  engine/block.ts
  engine/errors.ts
  engine/fresh/defaults.ts
  engine/schema/schemeable.ts
  mod.ts
  pages/LivePage.tsx
Labels: enhancement

#261 Fetch draft pages only when experimenting between multiple pages
  engine/releases/pages.ts
Labels: enhancement

#264 Use state loader instead of manually mounting middleware state
  deno.lock
  engine/releases/pages.ts
  handlers/routesSelection.ts
  loaders/state.ts
Labels: enhancement

#266 Add server-side invoke
  blocks/utils.ts
  clients/withManifest.ts
  engine/core/resolver.ts
  mod.ts
  types.ts
Labels: enhancement

#268 Add fncontext for inline loaders
  blocks/section.ts
  blocks/utils.ts
Labels: bug
