Repository deco-cx/deco, pull requests merged in 2023-06, with the labels that each got.

#270 Add singleflight and avoid forcing fresh on state load
  blocks/route.ts
  routes/live/_meta.ts
Labels: enhancement

#271 Start title with #
  matchers/MatchDevice.ts
  routes/live/_meta.ts
Labels: ignore-for-release

#273 Use naive solution for searching for saved blocks
  blocks/section.ts
  engine/schema/schemeable.ts
  routes/live/_meta.ts
Labels: ignore-for-release

#274 Fix go to page when site id is not defined
  components/LiveControls.tsx
  routes/live/_meta.ts
Labels: enhancement

#276 Fix path on previews
  routes/live/previews/[...block].tsx
Labels: enhancement

#277 Set current revision using sha256 of stringified json
  engine/releases/fs.ts
  engine/releases/supabaseProvider.ts
  routes/live/_meta.ts
  utils/encoding.ts
Labels: enhancement

#278 Add audiences title
  deno.lock
  handlers/routesSelection.ts
  schemas.gen.json
Labels: enhancement

#283 fix: selected block path from resolve chain
  components/LivePageEditor.tsx
Labels: bug

#296 feat: Handle formdata at preview
  components/LivePageShowcase.tsx
  pages/LivePage.tsx
  routes/live/previews/[...block].tsx
  sections/PageInclude.tsx
Labels: enhancement

#295 Fix Firefox json viewer.
  components/JsonViewer.tsx
Labels: bug

#308 feat: scroll into newly edited section
  components/LiveControls.tsx
Labels: enhancement

#247 Fix resolve chain for preview pages
  blocks/section.ts
  blocks/utils.ts
  compatibility/v0/editorData.ts
  components/LiveAnalytics.tsx
  components/LivePageEditor.tsx
  engine/block.ts
  engine/core/resolver.ts
  engine/fresh/manifest.ts
  handlers/devPage.ts
  meta.json
  pages/LivePage.tsx
  routes/_middleware.ts
  routes/live/invoke/[...key].ts
  routes/live/previews/index.tsx
Labels: bug

#310 fix: insert before at
  components/LivePageEditor.tsx
Labels: bug

#313 fix: make dot work again
  components/LiveControls.tsx
  pages/LivePage.tsx
  schemas.gen.json
Labels: bug

#317 Fix Cron Matcher title
  matchers/MatchCron.ts
  schemas.gen.json
Labels: documentation

#314 Long live to hints! No more max-depth on resolve & 3x faster
  .github/workflows/ci.yaml
  blocks/route.ts
  engine/block.ts
  engine/core/README.md
  engine/core/hints.test.expected.json
  engine/core/hints.test.json
  engine/core/hints.test.ts
  engine/core/hints.ts
  engine/core/mod.bench.ts
  engine/core/mod.test.ts
  engine/core/mod.ts
  engine/core/resolver.ts
  engine/fresh/defaults.ts
  engine/fresh/manifest.ts
  engine/fresh/manifestBuilder.ts
  engine/releases/fs.ts
  engine/releases/provider.ts
  engine/releases/supabaseProvider.ts
  engine/schema/gen.ts
  flags/audience.ts
  flags/everyone.ts
  handlers/routesSelection.ts
  import_map.json
  live.gen.ts
  meta.json
  pages/LivePage.tsx
  routes/live/_meta.ts
  routes/live/previews/[...block].tsx
  schemas.gen.json
  utils/object.ts
Labels: enhancement

#320 feat: remove showcase
  components/LivePageShowcase.tsx
  pages/LivePage.tsx
  schemas.gen.json
Labels: enhancement

#326 Support redirect params
  blocks/flag.ts
  deps.ts
  handlers/redirect.ts
Labels: enhancement
